Repository Yanol-Market/backend, pull requests merged in 2024-01, with the labels that each got.

#5 Feature/1 Redis 설정
  build.gradle
  src/main/java/site/goldenticket/common/redis/config/EmbeddedRedisConfig.java
  src/main/java/site/goldenticket/common/redis/config/RedisConfig.java
  src/main/java/site/goldenticket/common/redis/service/RedisService.java
  src/main/java/site/goldenticket/common/redis/service/RedisServiceImpl.java
  src/test/java/site/goldenticket/common/RedisServiceTest.java
Labels: enhancement

#7 Feature/1 CICD 설정
  .github/workflows/dev_CD.yml
  .github/workflows/dev_CI.yml
  Dockerfile
  build.gradle
  src/main/resources/application-dev.yml
Labels: enhancement

#2 #1 프로젝트 기본 세팅
  .github/workflows/dev_CD.yml
  .github/workflows/dev_CI.yml
  .gitignore
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/site/goldenticket/GoldenTicketApplication.java
  src/main/java/site/goldenticket/common/exception/CustomException.java
  src/main/java/site/goldenticket/common/redis/config/EmbeddedRedisConfig.java
  src/main/java/site/goldenticket/common/redis/config/RedisConfig.java
  src/main/java/site/goldenticket/common/redis/service/RedisService.java
  src/main/java/site/goldenticket/common/redis/service/RedisServiceImpl.java
  src/main/java/site/goldenticket/common/response/CommonResponse.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/response/GlobalExceptionHandler.java
  src/main/java/site/goldenticket/common/response/Status.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/site/goldenticket/GoldenTicketApplicationTests.java
  src/test/java/site/goldenticket/common/ApiDocumentation.java
  src/test/java/site/goldenticket/common/RedisServiceTest.java
Labels: good first issue

#17 Feature/14 nego package
  build.gradle
  src/main/java/site/goldenticket/domain/nego/controller/NegoController.java
  src/main/java/site/goldenticket/domain/nego/dto/buyer/request/PricePurposeRequest.java
  src/main/java/site/goldenticket/domain/nego/dto/buyer/response/PricePurposeResponse.java
  src/main/java/site/goldenticket/domain/nego/entity/Nego.java
  src/main/java/site/goldenticket/domain/nego/repository/NegoRepository.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/nego/status/NegotiationStatus.java
Labels: enhancement

#22 Spring Security 인증 구현
  build.gradle
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/security/authentication/AuthenticationConfigurer.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationFailureHandler.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationFilter.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
  src/main/java/site/goldenticket/common/security/authentication/dto/LoginRequest.java
  src/main/java/site/goldenticket/common/security/exception/InvalidAuthenticationArgumentException.java
  src/main/java/site/goldenticket/domain/security/PrincipalDetails.java
  src/main/java/site/goldenticket/domain/security/service/SecurityService.java
  src/main/java/site/goldenticket/domain/user/entity/RoleType.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
  src/test/java/site/goldenticket/common/ApiTest.java
  src/test/java/site/goldenticket/common/DatabaseCleaner.java
  src/test/java/site/goldenticket/common/DatabaseClearExtension.java
  src/test/java/site/goldenticket/common/SecurityTest.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
Labels: enhancement

#29 Spring Security 인가 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationFailureHandler.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
  src/main/java/site/goldenticket/common/security/authentication/TokenProvider.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityAccessDeniedHandler.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityAuthenticationEntryPoint.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityErrorCode.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
  src/main/java/site/goldenticket/common/security/exception/InvalidJwtException.java
  src/main/resources/application.yml
Labels: enhancement

#28 JWT 구현
  build.gradle
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationFailureHandler.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
  src/main/java/site/goldenticket/common/security/authentication/TokenProvider.java
  src/main/java/site/goldenticket/common/security/authentication/dto/AuthenticationToken.java
  src/main/java/site/goldenticket/common/security/authentication/dto/Token.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityAccessDeniedHandler.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityAuthenticationEntryPoint.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityErrorCode.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
  src/main/java/site/goldenticket/common/security/exception/InvalidJwtException.java
  src/main/resources/application.yml
  src/test/java/site/goldenticket/common/security/TokenProviderTest.java
Labels: enhancement

#13 Feature/11 Spring Security 설정 및 로그인
  build.gradle
  src/main/java/site/goldenticket/common/redis/config/EmbeddedRedisConfig.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/response/GlobalExceptionHandler.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/security/authentication/AuthenticationConfigurer.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationFailureHandler.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationFilter.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
  src/main/java/site/goldenticket/common/security/authentication/TokenProvider.java
  src/main/java/site/goldenticket/common/security/authentication/dto/AuthenticationToken.java
  src/main/java/site/goldenticket/common/security/authentication/dto/LoginRequest.java
  src/main/java/site/goldenticket/common/security/authentication/dto/Token.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityAccessDeniedHandler.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityAuthenticationEntryPoint.java
  src/main/java/site/goldenticket/common/security/authorization/SecurityErrorCode.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
  src/main/java/site/goldenticket/common/security/exception/InvalidAuthenticationArgumentException.java
  src/main/java/site/goldenticket/common/security/exception/InvalidJwtException.java
  src/main/java/site/goldenticket/domain/security/PrincipalDetails.java
  src/main/java/site/goldenticket/domain/security/service/SecurityService.java
  src/main/java/site/goldenticket/domain/user/entity/RoleType.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/test/java/site/goldenticket/common/ApiTest.java
  src/test/java/site/goldenticket/common/DatabaseCleaner.java
  src/test/java/site/goldenticket/common/DatabaseClearExtension.java
  src/test/java/site/goldenticket/common/SecurityTest.java
  src/test/java/site/goldenticket/common/security/TokenProviderTest.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
Labels: enhancement

#38 feature/common 공통 설정 추가
  src/main/java/site/goldenticket/common/entiy/BaseTimeEntity.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
  src/main/java/site/goldenticket/common/security/exception/SaveTokenException.java
  src/main/java/site/goldenticket/domain/user/entity/Delete.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/resources/script/schema.sql
  src/test/java/site/goldenticket/common/SecurityTest.java
  src/test/java/site/goldenticket/common/TokenProviderTest.java
  src/test/java/site/goldenticket/common/config/ApiDocumentation.java
  src/test/java/site/goldenticket/common/config/ApiTest.java
  src/test/java/site/goldenticket/common/config/DatabaseCleaner.java
  src/test/java/site/goldenticket/common/config/DatabaseClearExtension.java
Labels: enhancement

#53 회원가입 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/AgreementRequest.java
  src/main/java/site/goldenticket/domain/user/dto/JoinRequest.java
  src/main/java/site/goldenticket/domain/user/dto/JoinResponse.java
  src/main/java/site/goldenticket/domain/user/entity/Agreement.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#49 중복 확인 로직 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/AgreementRequest.java
  src/main/java/site/goldenticket/domain/user/dto/JoinRequest.java
  src/main/java/site/goldenticket/domain/user/dto/JoinResponse.java
  src/main/java/site/goldenticket/domain/user/entity/Agreement.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#48 Feature/39 회원가입
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/AgreementRequest.java
  src/main/java/site/goldenticket/domain/user/dto/JoinRequest.java
  src/main/java/site/goldenticket/domain/user/dto/JoinResponse.java
  src/main/java/site/goldenticket/domain/user/entity/Agreement.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#36 Feature/14 scheduled
  src/main/java/site/goldenticket/GoldenTicketApplication.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/nego/controller/NegoController.java
  src/main/java/site/goldenticket/domain/nego/dto/response/NegoResponse.java
  src/main/java/site/goldenticket/domain/nego/entity/Nego.java
  src/main/java/site/goldenticket/domain/nego/repository/NegoRepository.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/nego/service/SchedulerService.java
  src/main/java/site/goldenticket/domain/nego/status/NegotiationStatus.java
Labels: enhancement

#61 야놀자 로그인 구현
  src/main/java/site/goldenticket/common/response/CommonResponse.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
  src/main/java/site/goldenticket/common/security/authentication/dto/AuthenticationToken.java
  src/main/java/site/goldenticket/common/security/authentication/token/TokenProvider.java
  src/main/java/site/goldenticket/common/security/authentication/token/TokenService.java
  src/main/java/site/goldenticket/common/security/authentication/token/TokenServiceImpl.java
  src/main/java/site/goldenticket/common/security/authentication/token/dto/Token.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
  src/main/java/site/goldenticket/domain/security/controller/SecurityController.java
  src/main/java/site/goldenticket/domain/security/dto/YanoljaUserResponse.java
  src/main/java/site/goldenticket/domain/security/service/SecurityService.java
  src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
  src/main/java/site/goldenticket/dummy/yauser/model/YaUser.java
  src/main/java/site/goldenticket/dummy/yauser/service/YaUserService.java
  src/main/resources/script/schema.sql
  src/test/java/site/goldenticket/common/TokenProviderTest.java
Labels: enhancement

#57 Feature/41 야놀자 로그인 구현
  src/main/java/site/goldenticket/common/response/CommonResponse.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/security/authentication/SecurityAuthenticationSuccessHandler.java
  src/main/java/site/goldenticket/common/security/authentication/dto/AuthenticationToken.java
  src/main/java/site/goldenticket/common/security/authentication/token/TokenProvider.java
  src/main/java/site/goldenticket/common/security/authentication/token/TokenService.java
  src/main/java/site/goldenticket/common/security/authentication/token/TokenServiceImpl.java
  src/main/java/site/goldenticket/common/security/authentication/token/dto/Token.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorityConfigurer.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
  src/main/java/site/goldenticket/domain/security/controller/SecurityController.java
  src/main/java/site/goldenticket/domain/security/dto/YanoljaUserResponse.java
  src/main/java/site/goldenticket/domain/security/service/SecurityService.java
  src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
  src/main/java/site/goldenticket/domain/yauser/controller/YaUserController.java
  src/main/java/site/goldenticket/domain/yauser/service/YaUserService.java
  src/main/java/site/goldenticket/dummy/yauser/controller/YaUserController.java
  src/main/java/site/goldenticket/dummy/yauser/dto/YaUserRequest.java
  src/main/java/site/goldenticket/dummy/yauser/dto/YaUserResponse.java
  src/main/java/site/goldenticket/dummy/yauser/model/YaUser.java
  src/main/java/site/goldenticket/dummy/yauser/repository/YaUserRepository.java
  src/main/java/site/goldenticket/dummy/yauser/service/YaUserService.java
  src/main/resources/script/schema.sql
  src/test/java/site/goldenticket/common/TokenProviderTest.java
Labels: enhancement

#63 Hotfix: 회원가입 휴대폰 번호 포맷 변경
  src/main/java/site/goldenticket/domain/user/dto/JoinRequest.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
Labels: bug

#68 feat: 채팅 패키지 설계
  src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
  src/main/java/site/goldenticket/domain/chat/entity/Chat.java
  src/main/java/site/goldenticket/domain/chat/entity/ChatRoom.java
  src/main/java/site/goldenticket/domain/chat/entity/SenderType.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRepository.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRoomRepository.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: enhancement

#72 fix: Token 검증 필터에서 Redis 조회할 때, Prefix 제거
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/authorization/TokenAuthorizationFilter.java
  src/main/java/site/goldenticket/common/security/exception/InvalidJwtException.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
Labels: bug

#69 Feature/58 chat room detail 채팅방 상세 조회
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomDetailResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomInfoResponse.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRepository.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
Labels: enhancement

#74 feat: 채팅방 목록 조회 API 구현
  src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomListResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomShortResponse.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRepository.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRoomRepository.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/product/model/Product.java
  src/main/java/site/goldenticket/domain/product/repository/ProductRepository.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
Labels: enhancement

#75 feat: 채팅 등록 API 구현
  src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRequest.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: enhancement

#79 feat: 채팅 조회여부 관리 기능 구현
  src/main/java/site/goldenticket/domain/chat/dto/ChatResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomShortResponse.java
  src/main/java/site/goldenticket/domain/chat/entity/Chat.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: enhancement

#77 Feature/76 채팅 DB 수정
  src/main/resources/script/schema.sql
Labels: bug, documentation

#89 Feature/12 save order
  src/main/java/site/goldenticket/common/constants/OrderStatus.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/nego/entity/Nego.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/payment/controller/PaymentController.java
  src/main/java/site/goldenticket/domain/payment/dto/response/PaymentDetailResponse.java
  src/main/java/site/goldenticket/domain/payment/model/Order.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
Labels: enhancement

#85 Feature/14 nego refactoring
  src/main/java/site/goldenticket/common/redis/service/RedisServiceImpl.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/nego/controller/NegoController.java
  src/main/java/site/goldenticket/domain/nego/dto/request/PriceProposeRequest.java
  src/main/java/site/goldenticket/domain/nego/dto/response/HandoverResponse.java
  src/main/java/site/goldenticket/domain/nego/dto/response/PayResponse.java
  src/main/java/site/goldenticket/domain/nego/dto/response/PriceProposeResponse.java
  src/main/java/site/goldenticket/domain/nego/entity/Nego.java
  src/main/java/site/goldenticket/domain/nego/repository/NegoRepository.java
  src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
Labels: enhancement

#66 Feature/56 알림 관련 API 구현
  src/main/java/site/goldenticket/domain/alert/controller/AlertController.java
  src/main/java/site/goldenticket/domain/alert/dto/AlertListResponse.java
  src/main/java/site/goldenticket/domain/alert/dto/AlertResponse.java
  src/main/java/site/goldenticket/domain/alert/dto/AlertUnSeenResponse.java
  src/main/java/site/goldenticket/domain/alert/entity/Alert.java
  src/main/java/site/goldenticket/domain/alert/repository/AlertRepository.java
  src/main/java/site/goldenticket/domain/alert/service/AlertService.java
Labels: enhancement

#80 Feature/12 결제 기능
  .github/workflows/dev_CD.yml
  .github/workflows/dev_CI.yml
  .gitignore
  build.gradle
  src/main/java/site/goldenticket/common/constants/OrderStatus.java
  src/main/java/site/goldenticket/common/constants/PaymentStatus.java
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/common/utils/Converter.java
  src/main/java/site/goldenticket/domain/nego/entity/Nego.java
  src/main/java/site/goldenticket/domain/nego/repository/NegoRepository.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/payment/config/IamportApiProperty.java
  src/main/java/site/goldenticket/domain/payment/config/IamportConfig.java
  src/main/java/site/goldenticket/domain/payment/controller/PaymentController.java
  src/main/java/site/goldenticket/domain/payment/dto/request/PaymentRequest.java
  src/main/java/site/goldenticket/domain/payment/dto/response/PaymentDetailResponse.java
  src/main/java/site/goldenticket/domain/payment/dto/response/PaymentReadyResponse.java
  src/main/java/site/goldenticket/domain/payment/dto/response/PaymentResponse.java
  src/main/java/site/goldenticket/domain/payment/model/Order.java
  src/main/java/site/goldenticket/domain/payment/model/Payment.java
  src/main/java/site/goldenticket/domain/payment/model/PaymentCancelDetail.java
  src/main/java/site/goldenticket/domain/payment/repository/IamportRepository.java
  src/main/java/site/goldenticket/domain/payment/repository/OrderRepository.java
  src/main/java/site/goldenticket/domain/payment/repository/PaymentCancelDetailRepository.java
  src/main/java/site/goldenticket/domain/payment/repository/PaymentCancelMapper.java
  src/main/java/site/goldenticket/domain/payment/repository/PaymentMapper.java
  src/main/java/site/goldenticket/domain/payment/repository/PaymentRepository.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
  src/main/java/site/goldenticket/domain/product/model/Product.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/main/resources/script/schema.sql
Labels: enhancement

#97 feat: 테스트용 알림 등록 API 구현
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/domain/alert/controller/AlertController.java
  src/main/java/site/goldenticket/domain/alert/dto/AlertRequest.java
  src/main/java/site/goldenticket/domain/alert/service/AlertService.java
Labels: enhancement

#98 Feature/58 채팅 기능 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRequest.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomDetailResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomInfoResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomListResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/ChatRoomShortResponse.java
  src/main/java/site/goldenticket/domain/chat/entity/Chat.java
  src/main/java/site/goldenticket/domain/chat/entity/ChatRoom.java
  src/main/java/site/goldenticket/domain/chat/entity/SenderType.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRepository.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRoomRepository.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/product/repository/ProductRepository.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
Labels: enhancement

#103 Feature/59 네고 가능 여부 조회 기능 구현
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/controller/NegoController.java
  src/main/java/site/goldenticket/domain/nego/dto/response/NegoAvailableResponse.java
  src/main/java/site/goldenticket/domain/nego/repository/NegoRepository.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: enhancement

#104 feat: 네고 가능 여부 조회 API 응답값 추가(채팅방 ID)
  src/main/java/site/goldenticket/domain/chat/repository/ChatRoomRepository.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/dto/response/NegoAvailableResponse.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: enhancement

#111 Feature/108 관심 상품 삭제
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/main/java/site/goldenticket/domain/user/wish/controller/WishController.java
  src/main/java/site/goldenticket/domain/user/wish/entity/WishProduct.java
  src/main/java/site/goldenticket/domain/user/wish/repository/WishProductRepository.java
  src/main/java/site/goldenticket/domain/user/wish/repository/WishRepository.java
  src/main/java/site/goldenticket/domain/user/wish/service/WishService.java
  src/main/resources/script/schema.sql
  src/test/java/site/goldenticket/common/SecurityTest.java
  src/test/java/site/goldenticket/common/config/ApiTest.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
  src/test/java/site/goldenticket/domain/user/wish/controller/WishProductControllerTest.java
Labels: enhancement

#110 Feature/107 관심 상품 등록 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/common/response/GlobalExceptionHandler.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/main/java/site/goldenticket/domain/user/wish/controller/WishController.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishProductSaveRequest.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishProductSaveResponse.java
  src/main/java/site/goldenticket/domain/user/wish/entity/WishProduct.java
  src/main/java/site/goldenticket/domain/user/wish/repository/WishProductRepository.java
  src/main/java/site/goldenticket/domain/user/wish/service/WishService.java
  src/main/resources/script/schema.sql
  src/test/java/site/goldenticket/common/SecurityTest.java
  src/test/java/site/goldenticket/common/config/ApiTest.java
  src/test/java/site/goldenticket/common/utils/ProductUtils.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
  src/test/java/site/goldenticket/domain/user/wish/controller/WishProductControllerTest.java
Labels: enhancement

#113 Feature/58 chat viewed type 채팅 조회여부 타입 추가 및 주석 추가
  src/main/java/site/goldenticket/domain/chat/entity/Chat.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/resources/script/schema.sql
Labels: enhancement

#114 Feature/109 관심 상품 목록 조회 구현
  src/main/java/site/goldenticket/common/utils/DateUtil.java
  src/main/java/site/goldenticket/domain/product/dto/ProductDetailResponse.java
  src/main/java/site/goldenticket/domain/product/dto/ProductResponse.java
  src/main/java/site/goldenticket/domain/user/wish/controller/WishController.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishProductResponse.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishProductSaveResponse.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishProductsResponse.java
  src/main/java/site/goldenticket/domain/user/wish/repository/WishProductRepository.java
  src/main/java/site/goldenticket/domain/user/wish/service/WishService.java
  src/test/java/site/goldenticket/common/utils/ProductUtils.java
  src/test/java/site/goldenticket/domain/user/wish/controller/WishProductControllerTest.java
Labels: enhancement

#115 Feature/58 chat nego price 네고가 고려한 채팅방 가격 결정 메서드 구현
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/payment/repository/OrderRepository.java
Labels: enhancement

#116 Feature/58 채팅방 생성 API 구현 및 채팅 response 데이터 추가, request 매핑로직 수정 등 리팩토링
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/domain/chat/controller/ChatController.java
  src/main/java/site/goldenticket/domain/chat/dto/request/ChatRequest.java
  src/main/java/site/goldenticket/domain/chat/dto/request/ChatRoomRequest.java
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomDetailResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomInfoResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomListResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomResponse.java
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomShortResponse.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: enhancement

#117 Feature/58 chat db 채팅 DB 수정 (추후 원상복귀 예정)
  src/main/java/site/goldenticket/domain/chat/entity/Chat.java
  src/main/java/site/goldenticket/domain/chat/entity/ChatRoom.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRoomRepository.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/resources/script/schema.sql
Labels: bug

#118 Feature/chat db reset 채팅 DB 재수정
  src/main/java/site/goldenticket/domain/chat/entity/Chat.java
  src/main/resources/script/schema.sql
Labels: bug, documentation, enhancement

#120 feat: 채팅방 상세 조회 응답 DTO 데이터 수정
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomInfoResponse.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: enhancement

#123 Feature/14 nego final refactor
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/nego/controller/NegoController.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/product/model/Product.java
Labels: enhancement

#131 Feature/60 야놀자 로그인 응답 값 수정
  src/main/java/site/goldenticket/domain/security/controller/SecurityController.java
  src/main/java/site/goldenticket/domain/security/dto/YanoljaLoginResponse.java
  src/main/java/site/goldenticket/domain/security/service/SecurityService.java
Labels: enhancement

#133 Feature/44 사용자 정보 조회 구현
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/JoinResponse.java
  src/main/java/site/goldenticket/domain/user/dto/UserResponse.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#136 Feature/134 계좌 삭제 구현
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#135 Feature/42 계좌 등록 및 조회 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/security/dto/YanoljaLoginResponse.java
  src/main/java/site/goldenticket/domain/security/service/SecurityService.java
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/AccountResponse.java
  src/main/java/site/goldenticket/domain/user/dto/RegisterAccountRequest.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/common/config/ApiTest.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
  src/test/java/site/goldenticket/domain/user/wish/controller/WishProductControllerTest.java
Labels: enhancement

#150 Feature/127 OrderRepository JPA 쿼리 문제 수정
  src/main/java/site/goldenticket/domain/payment/repository/OrderRepository.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
Labels: bug

#151 Feature/127 매개변수 순서 불일치로 인한 에러 해결
  src/main/java/site/goldenticket/domain/product/service/ProductOrderService.java
Labels: bug

#152 Feature/12 구매내역 표시 여부 관련 변수명 수정
  src/main/java/site/goldenticket/domain/payment/model/Order.java
Labels: bug, documentation

#153 fix: customerViewCheck 기본값 false로
  src/main/java/site/goldenticket/domain/payment/model/Order.java
Labels: bug

#154 Feature/127 조회수가 존재하지 않는 상품에 대한 처리 추가
  src/main/java/site/goldenticket/domain/product/service/ProductSchedulerService.java
Labels: bug

#155 Feature/12 테이블 컬럼명 명시 삭제
  src/main/java/site/goldenticket/domain/payment/model/Order.java
  src/main/java/site/goldenticket/domain/payment/model/Payment.java
  src/main/java/site/goldenticket/domain/payment/model/PaymentCancelDetail.java
Labels: bug

#157 Feature/12
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: bug

#158 Feature/12 exception case
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: documentation

#159 Feature/12
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: enhancement

#162 Hotfix/161 야놀자 로그인 응답 수정
  src/main/java/site/goldenticket/domain/security/dto/YanoljaLoginResponse.java
  src/main/java/site/goldenticket/domain/security/service/SecurityService.java
Labels: bug

#67 Feature/60 관심지역 등록 및 조회
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/product/constants/AreaCode.java
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/AccountResponse.java
  src/main/java/site/goldenticket/domain/user/dto/UserResponse.java
  src/main/java/site/goldenticket/domain/user/dto/WishRegionResponse.java
  src/main/java/site/goldenticket/domain/user/dto/WishRegionsResponse.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/repository/UserRepository.java
  src/main/java/site/goldenticket/domain/user/repository/WishRegionRepository.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/main/java/site/goldenticket/domain/user/wish/controller/WishController.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishRegionListResponse.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishRegionRegisterRequest.java
  src/main/java/site/goldenticket/domain/user/wish/dto/WishRegionResponse.java
  src/main/java/site/goldenticket/domain/user/wish/entity/WishRegion.java
  src/main/java/site/goldenticket/domain/user/wish/service/WishService.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#166 Feature/165 비밀번호 변경 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/ChangePasswordRequest.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#168 feat: 채팅방 상세 조회 응답값 수정
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomInfoResponse.java
  src/main/java/site/goldenticket/domain/chat/repository/ChatRepository.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: enhancement

#170 Feature/12 결제이외의 관련 상태값들 변경
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: enhancement

#176 Hotfix/175 관심 상품 삭제 파라미터 수정
  src/main/java/site/goldenticket/domain/product/wish/controller/WishProductController.java
  src/main/java/site/goldenticket/domain/product/wish/repository/WishProductRepository.java
  src/main/java/site/goldenticket/domain/product/wish/service/WishProductService.java
  src/test/java/site/goldenticket/domain/product/wish/controller/WishProductControllerTest.java
Labels: bug

#177 Feature/169 채팅상태 추가(채팅방 상세 조회 API) 및 예외처리 (채팅, 채팅방 생성 API)
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: enhancement

#178 Hotfix/164 관심 지역 수정 구현
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/wish/service/WishRegionService.java
  src/test/java/site/goldenticket/domain/user/wish/controller/WishRegionControllerTest.java
Labels: bug

#179 Feature/12 결제 수정
  src/main/java/site/goldenticket/domain/payment/dto/response/PaymentDetailResponse.java
  src/main/java/site/goldenticket/domain/payment/model/Order.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: enhancement

#181 Feature/132 프로필 수정
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/ChangeProfileRequest.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/main/resources/script/schema.sql
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#184 Feature/121 네고 및 양도 관련 알림 생성
  src/main/java/site/goldenticket/domain/alert/controller/AlertController.java
  src/main/java/site/goldenticket/domain/alert/service/AlertService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: enhancement

#187 Feature/12
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: bug, enhancement

#188 채팅 500 에러 수정
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: bug

#193 feat: 채팅 테스트 api 접근 허용 경로 수정 및 네고 응답값 변경
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/domain/nego/controller/NegoController.java
  src/main/java/site/goldenticket/domain/nego/dto/response/NegoTestListResponse.java
  src/main/java/site/goldenticket/domain/nego/dto/response/NegoTestResponse.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: bug, enhancement

#194 Feature/183 chat room post 결제 완료 시, 채팅방 없으면 새로 생성
  src/main/java/site/goldenticket/domain/nego/dto/response/NegoAvailableResponse.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: enhancement

#197 Feature/196 채팅방 상태값 수정
  src/main/java/site/goldenticket/domain/product/service/ProductOrderService.java
Labels: bug

#199 Feature/195 검색 날짜 범위 조건 수정
  src/main/java/site/goldenticket/domain/product/repository/ProductRepositoryImpl.java
Labels: bug

#200 fix: 스케줄러 시간 조정
  src/main/java/site/goldenticket/common/scheduler/service/SchedulerService.java
Labels: bug

#202 Feature/45 회원탈퇴 구현
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/user/controller/UserController.java
  src/main/java/site/goldenticket/domain/user/dto/RemoveUserRequest.java
  src/main/java/site/goldenticket/domain/user/entity/Agreement.java
  src/main/java/site/goldenticket/domain/user/entity/DeleteReason.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/main/java/site/goldenticket/domain/user/service/UserService.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#203 Hotfix/93 야놀자 아이디 중복 연동 예외 처리
  src/main/java/site/goldenticket/domain/user/service/UserService.java
Labels: bug

#205 feat: 결제 완료 시, 새 채팅방 생성여부 및 채팅방 ID 함께 반환
  src/main/java/site/goldenticket/domain/payment/dto/response/PaymentResponse.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: enhancement

#208 feat: 채팅방 생성 시 필요한 채팅 저장
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/dto/response/NegoAvailableResponse.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/payment/dto/response/PaymentResponse.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: enhancement

#211 Feature/129 wishId 제거
  src/main/java/site/goldenticket/domain/product/dto/WishedProductResponse.java
Labels: bug

#213 Feature/12 양도 취소시 환불
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/payment/model/Payment.java
  src/main/java/site/goldenticket/domain/payment/model/PaymentCancelDetail.java
  src/main/java/site/goldenticket/domain/payment/repository/PaymentRepository.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
  src/main/java/site/goldenticket/domain/payment/service/PurchaseHistoryService.java
Labels: enhancement

#215 fix: 채팅방 상세 조회 - 채팅상태: 양도대기중 - 바로 결제인 경우 추가
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: bug

#218 feat: 결제 취소시 db에 취소 내역 저장
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: enhancement

#223 fix: 네고가능여부조회- 모든 경우 채팅방 ID 전달
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: bug

#227 feat: 시간초과 관련 재결제 시스템 메세지 생성
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
Labels: enhancement

#228 Feature/172 product 조회 및 삭제 테스트 코드 작성
  src/main/java/site/goldenticket/domain/payment/model/Order.java
  src/test/java/site/goldenticket/common/utils/ChatRoomUtils.java
  src/test/java/site/goldenticket/common/utils/ChatUtils.java
  src/test/java/site/goldenticket/common/utils/NegoUtils.java
  src/test/java/site/goldenticket/common/utils/OrderUtils.java
  src/test/java/site/goldenticket/domain/product/controller/ProductControllerTest.java
Labels: enhancement

#229 fix: 채팅방 상세 조회시, 채팅 상세 로직 수정
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/payment/repository/OrderRepository.java
Labels: bug

#230 Feature 테스트에서 공통으로 사용하기 위한 utils 생성
  src/test/java/site/goldenticket/common/SecurityTest.java
  src/test/java/site/goldenticket/common/utils/RestAssuredUtils.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#231 Feat/12 결제완료 삭제 내역은 응답값에서 제외
  src/main/java/site/goldenticket/domain/payment/service/PurchaseHistoryService.java
Labels: enhancement

#232 feat: 자동 양도완료(양도승인)관련 시스템 메세지 전송
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
Labels: enhancement

#236 Feature/12 mobile payment
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/repository/NegoRepository.java
  src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/payment/controller/PaymentController.java
  src/main/java/site/goldenticket/domain/payment/dto/request/PaymentRequest.java
  src/main/java/site/goldenticket/domain/payment/model/Order.java
  src/main/java/site/goldenticket/domain/payment/repository/OrderRepository.java
  src/main/java/site/goldenticket/domain/payment/repository/PaymentCancelMapper.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
  src/main/java/site/goldenticket/domain/payment/service/PurchaseHistoryService.java
  src/main/java/site/goldenticket/domain/product/constants/NegoProductStatus.java
  src/main/java/site/goldenticket/domain/product/dto/ProductCompletedSoldOutResponse.java
  src/main/java/site/goldenticket/domain/product/dto/ProductDetailResponse.java
  src/main/java/site/goldenticket/domain/product/service/ProductOrderService.java
  src/test/java/site/goldenticket/common/SecurityTest.java
  src/test/java/site/goldenticket/common/utils/ChatRoomUtils.java
  src/test/java/site/goldenticket/common/utils/ChatUtils.java
  src/test/java/site/goldenticket/common/utils/NegoUtils.java
  src/test/java/site/goldenticket/common/utils/OrderUtils.java
  src/test/java/site/goldenticket/common/utils/RestAssuredUtils.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/payment/repository/PaymentCancelMapperTest.java
  src/test/java/site/goldenticket/domain/product/controller/ProductControllerTest.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#237 Feature/12 모바일 결제
  src/main/java/site/goldenticket/domain/payment/controller/PaymentController.java
  src/main/java/site/goldenticket/domain/payment/dto/request/PaymentRequest.java
Labels: enhancement

#238 Feature/233 알림 내용 변경
  src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
  src/main/java/site/goldenticket/domain/payment/service/PaymentService.java
Labels: bug

#239 Feature/12 자동 양도 완료 관련 수정
  src/main/java/site/goldenticket/domain/nego/service/NegoSchedulerService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: bug, enhancement

#242 feat: 채팅방 상세 조회 응답값 추가(네고가능여부)
  src/main/java/site/goldenticket/domain/chat/dto/response/ChatRoomInfoResponse.java
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
  src/main/java/site/goldenticket/domain/nego/service/NegoServiceImpl.java
Labels: bug

#245 feat: 채팅방 상세 조회- 한국시간으로 변경, 자동 양도 완료 시, 정산안내 시스템 메세지 전송
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: enhancement

#246 Feature/사용자 단위 테스트
  src/main/java/site/goldenticket/common/response/ErrorCode.java
  src/main/java/site/goldenticket/domain/user/entity/User.java
  src/test/java/site/goldenticket/common/config/ApiTest.java
  src/test/java/site/goldenticket/common/utils/UserUtils.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
  src/test/java/site/goldenticket/domain/user/entity/UserTest.java
  src/test/java/site/goldenticket/domain/user/service/UserServiceTest.java
Labels: enhancement

#247 fix: 채팅 작성 시간 한국시간으로 변환 로직 오류 해결
  src/main/java/site/goldenticket/domain/chat/service/ChatService.java
Labels: bug

#248 Feature/ Spring REST Docs 공통 설정
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user.adoc
  src/test/java/site/goldenticket/common/config/ApiDocumentation.java
  src/test/java/site/goldenticket/common/config/ApiTest.java
  src/test/java/site/goldenticket/domain/user/controller/UserControllerTest.java
Labels: enhancement

#249 Documents README 작성
  README.md
Labels: documentation

#254 docs: 야놀자 연동 상품 등록 관련 api 명세 작성
  src/docs/asciidoc/product.adoc
  src/main/java/site/goldenticket/common/security/SecurityConfiguration.java
  src/main/java/site/goldenticket/domain/product/service/ProductService.java
  src/main/java/site/goldenticket/dummy/reservation/controller/MockReservationController.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/site/goldenticket/domain/product/controller/ProductControllerTest.java
Labels: documentation
